<?php
/**
 * KYA Food Production - Inventory Report Export
 * Export inventory reports in PDF, Excel, and CSV formats
 */

require_once '../../config/database.php';
require_once '../../config/constants.php';
require_once '../../config/session.php';
require_once '../../includes/functions.php';

SessionManager::start();
SessionManager::requireLogin();

if (!SessionManager::hasPermission('reports_view')) {
    die('Access denied');
}

$userInfo = SessionManager::getUserInfo();
$db = new Database();
$conn = $db->connect();

// Get parameters
$format = $_GET['export'] ?? 'pdf';
$section = $_GET['section'] ?? '';
$category = $_GET['category'] ?? '';
$status = $_GET['status'] ?? '';
$alertLevel = $_GET['alert_level'] ?? '';

// Build WHERE clause
$whereConditions = [];
$params = [];

if ($section) {
    $whereConditions[] = "section = ?";
    $params[] = $section;
}

if ($category) {
    $whereConditions[] = "category = ?";
    $params[] = $category;
}

if ($status) {
    $whereConditions[] = "status = ?";
    $params[] = $status;
}

if ($alertLevel) {
    if ($alertLevel === 'critical') {
        $whereConditions[] = "alert_status = 'critical'";
    } elseif ($alertLevel === 'low') {
        $whereConditions[] = "alert_status = 'low_stock'";
    } elseif ($alertLevel === 'normal') {
        $whereConditions[] = "(alert_status IS NULL OR alert_status = 'normal')";
    }
}

$whereClause = !empty($whereConditions) ? 'WHERE ' . implode(' AND ', $whereConditions) : '';

try {
    // Get inventory statistics
    $statsStmt = $conn->prepare("
        SELECT 
            COUNT(*) as total_items,
            SUM(quantity) as total_quantity,
            SUM(quantity * COALESCE(unit_price, 0)) as total_value,
            COUNT(CASE WHEN alert_status = 'critical' THEN 1 END) as critical_items,
            COUNT(CASE WHEN alert_status = 'low_stock' THEN 1 END) as low_stock_items,
            COUNT(CASE WHEN status = 'active' THEN 1 END) as active_items
        FROM inventory
        $whereClause
    ");
    $statsStmt->execute($params);
    $stats = $statsStmt->fetch(PDO::FETCH_ASSOC);
    
    // Get inventory items
    $itemsStmt = $conn->prepare("
        SELECT 
            item_code,
            item_name,
            category,
            section,
            quantity,
            unit,
            COALESCE(unit_price, 0) as unit_price,
            (quantity * COALESCE(unit_price, 0)) as total_value,
            COALESCE(reorder_level, 0) as reorder_level,
            COALESCE(critical_level, 0) as critical_level,
            status,
            alert_status,
            location,
            created_at
        FROM inventory
        $whereClause
        ORDER BY section, category, item_name
    ");
    $itemsStmt->execute($params);
    $items = $itemsStmt->fetchAll(PDO::FETCH_ASSOC);
    
} catch (Exception $e) {
    die('Error fetching data: ' . $e->getMessage());
}

// Export based on format
if ($format === 'csv') {
    // CSV Export
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="inventory_report_' . date('Y-m-d_His') . '.csv"');
    header('Pragma: no-cache');
    header('Expires: 0');
    
    $output = fopen('php://output', 'w');
    fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF)); // UTF-8 BOM
    
    // Header
    fputcsv($output, ['KYA Food Production - Inventory Report']);
    fputcsv($output, ['Generated', date('Y-m-d H:i:s')]);
    fputcsv($output, ['Generated By', $userInfo['full_name']]);
    fputcsv($output, []);
    
    // Statistics
    fputcsv($output, ['Inventory Summary']);
    fputcsv($output, ['Total Items', number_format($stats['total_items'])]);
    fputcsv($output, ['Total Quantity', number_format($stats['total_quantity'], 2)]);
    fputcsv($output, ['Total Value', 'Rs. ' . number_format($stats['total_value'], 2)]);
    fputcsv($output, ['Active Items', number_format($stats['active_items'])]);
    fputcsv($output, ['Critical Items', number_format($stats['critical_items'])]);
    fputcsv($output, ['Low Stock Items', number_format($stats['low_stock_items'])]);
    fputcsv($output, []);
    
    // Items table
    fputcsv($output, ['Inventory Items']);
    fputcsv($output, ['Item Code', 'Item Name', 'Category', 'Section', 'Quantity', 'Unit', 'Unit Price', 'Total Value', 'Reorder Level', 'Critical Level', 'Status', 'Alert Status', 'Location']);
    
    foreach ($items as $item) {
        fputcsv($output, [
            $item['item_code'],
            $item['item_name'],
            $item['category'],
            'Section ' . $item['section'],
            number_format($item['quantity'], 2),
            $item['unit'],
            'Rs. ' . number_format($item['unit_price'], 2),
            'Rs. ' . number_format($item['total_value'], 2),
            number_format($item['reorder_level'], 2),
            number_format($item['critical_level'], 2),
            $item['status'],
            $item['alert_status'] ?: 'Normal',
            $item['location']
        ]);
    }
    
    fclose($output);
    exit();
}

elseif ($format === 'pdf') {
    // PDF Export (HTML with print styling)
    ?>
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Inventory Report</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            h1 { color: #2c5f41; border-bottom: 3px solid #2c5f41; padding-bottom: 10px; }
            h2 { color: #4a8b3a; margin-top: 30px; }
            table { width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 12px; }
            th { background: #2c5f41; color: white; padding: 10px; text-align: left; }
            td { padding: 8px; border-bottom: 1px solid #ddd; }
            tr:hover { background: #f5f5f5; }
            .summary-box { background: #f8f9fa; padding: 15px; border-left: 4px solid #2c5f41; margin: 20px 0; }
            .stat-row { display: flex; justify-content: space-between; padding: 5px 0; }
            .stat-label { font-weight: bold; }
            .stat-value { color: #2c5f41; font-weight: bold; }
            .alert-critical { color: #dc3545; font-weight: bold; }
            .alert-low { color: #ffc107; font-weight: bold; }
            @media print {
                body { margin: 0; }
                button { display: none; }
            }
        </style>
    </head>
    <body>
        <h1>KYA Food Production - Inventory Report</h1>
        <p><strong>Generated:</strong> <?php echo date('Y-m-d H:i:s'); ?></p>
        <p><strong>Generated By:</strong> <?php echo htmlspecialchars($userInfo['full_name']); ?></p>
        
        <div class="summary-box">
            <h2>Inventory Summary</h2>
            <div class="stat-row">
                <span class="stat-label">Total Items:</span>
                <span class="stat-value"><?php echo number_format($stats['total_items']); ?></span>
            </div>
            <div class="stat-row">
                <span class="stat-label">Total Quantity:</span>
                <span class="stat-value"><?php echo number_format($stats['total_quantity'], 2); ?></span>
            </div>
            <div class="stat-row">
                <span class="stat-label">Total Value:</span>
                <span class="stat-value">Rs. <?php echo number_format($stats['total_value'], 2); ?></span>
            </div>
            <div class="stat-row">
                <span class="stat-label">Active Items:</span>
                <span class="stat-value"><?php echo number_format($stats['active_items']); ?></span>
            </div>
            <div class="stat-row">
                <span class="stat-label">Critical Items:</span>
                <span class="stat-value alert-critical"><?php echo number_format($stats['critical_items']); ?></span>
            </div>
            <div class="stat-row">
                <span class="stat-label">Low Stock Items:</span>
                <span class="stat-value alert-low"><?php echo number_format($stats['low_stock_items']); ?></span>
            </div>
        </div>
        
        <h2>Inventory Items</h2>
        <table>
            <thead>
                <tr>
                    <th>Code</th>
                    <th>Item Name</th>
                    <th>Category</th>
                    <th>Section</th>
                    <th>Quantity</th>
                    <th>Unit Price</th>
                    <th>Total Value</th>
                    <th>Alert</th>
                </tr>
            </thead>
            <tbody>
                <?php if (empty($items)): ?>
                <tr>
                    <td colspan="8" style="text-align: center;">No inventory items found</td>
                </tr>
                <?php else: ?>
                    <?php foreach ($items as $item): ?>
                    <tr>
                        <td><?php echo htmlspecialchars($item['item_code']); ?></td>
                        <td><?php echo htmlspecialchars($item['item_name']); ?></td>
                        <td><?php echo htmlspecialchars($item['category']); ?></td>
                        <td>Section <?php echo $item['section']; ?></td>
                        <td><?php echo number_format($item['quantity'], 2); ?> <?php echo htmlspecialchars($item['unit']); ?></td>
                        <td>Rs. <?php echo number_format($item['unit_price'], 2); ?></td>
                        <td>Rs. <?php echo number_format($item['total_value'], 2); ?></td>
                        <td>
                            <?php if ($item['alert_status'] === 'critical'): ?>
                                <span class="alert-critical">CRITICAL</span>
                            <?php elseif ($item['alert_status'] === 'low_stock'): ?>
                                <span class="alert-low">LOW STOCK</span>
                            <?php else: ?>
                                Normal
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
            </tbody>
        </table>
        
        <script>
            window.onload = function() {
                window.print();
            };
        </script>
    </body>
    </html>
    <?php
    exit();
}

else {
    die('Invalid export format');
}
?>
